baseURL: http://www.mikiwang.netlify.app/
title: Miki Wang
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
params:
  author: Miki Wang
  avatarurl: images/avatar1.jpg
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  csp:
    childsrc: '''self'''
    connectsrc:
      - '''self'''
      - https://www.google-analytics.com
    fontsrc:
      - '''self'''
      - https://fonts.gstatic.com
      - https://cdn.jsdelivr.net/
    formaction: '''self'''
    framesrc: '''self'''
    imgsrc: '''self'''
    objectsrc: '''none'''
    prefetchsrc: '''self'''
    scriptsrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://www.google-analytics.com
    stylesrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://fonts.googleapis.com/
      - https://cdn.jsdelivr.net/
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Miki Wang's personal website
  enableTwemoji: no
  footerContent: Love this world.
  hideColorSchemeToggle: no
  hideCopyright: no
  hideCredits: no
  hideFooter: no
  info: Data Science Enthusiast and Cat Lover
  keywords: blog,data science,personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2021
  social:
    - icon: fa fa-github
      name: Github
      url: https://github.com/mikiya2014/
      weight: 1
    - icon: fa fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/yu-wang-mikiya/
      weight: 2
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Contact me
          url: contact/
          weight: 5
